DirectoryPath: "private"
EnforceHTTPS: true
IgnoreURLs: "https://www.markbook.com/"
IgnoreDirs: "/"
CheckLinks: true
CheckImages: true
CheckScripts: true
CheckGeneric: true
CheckExternal: true
IgnoreInternalEmptyHash: false
IgnoreEmptyHref: false
IgnoreDirectoryMissingTrailingSlash: true
