name: Begin Algolia crawl

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  compile:
    name: Compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1

      - name: Install dependencies
        run: npm install puppeteer

      - name: Compile TypeScript
        run: npm install typescript && npx tsc link_checker.ts

      - name: Run API docs link checker
        run: node crawl-api-links.ts

