name: Crawl API docs links

on:
  pull_request:
    branches:
      - production

jobs:
  compile:
    name: Compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run API docs link checker
        run: pnpm run crawl-api-links

