name: Crawl API docs links

on:
  pull_request:
    branches:
      - production
  workflow_dispatch:

jobs:
  compile:
    name: Compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.1

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run API docs link checker
        id: check-api-links
        run: npm run crawl-api-links

      - name: Create issue
        needs: check-api-links
        runs-on: ubuntu-latest

        env:
          EXPORTED_VARIABLE: ${{ needs.export_variable_step.outputs.broken_links }}
        if: env.EXPORTED_VARIABLE
        run: |
          # Create the issue and reference the exported variable
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"title": "Broken API docs links", "body": "The exported variable value is: '${EXPORTED_VARIABLE}'", "assignees": ["kodster28"]}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues"

